deployment:
  tasks:
    - export DEPLOYPATH=/home/a7c4mi1pv4t6/repositories/rachelbatson.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp bootstrap-comingsoon.css $DEPLOYPATH
    
