deployment:
  tasks:
    - export DEPLOYPATH=/home/n6tfm0c831ns/repositories/rachelbatson.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp bootstrap-comingsoon.css $DEPLOYPATH
    
